package com.hipermidia.model.states;

public enum GameStates {
    INIT, FIGHTING, RESOLVINGPUZZLE, TALKINGNPC, USINGITEM, LEAVINGROOM, SHOWINGLOCATION, SHOWINGTURN, SHOWHELP, SHOWINGSTATUS, SHOWINGINVENTORY, DEFEATED, ENDING
}
