package com.hipermidia.model.states;

public enum GameStates {
    INIT, FIGHTING, RESOLVINGPUZZLE, TALKINGNPC, USINGITEM, LEAVINGROOM, SHOWINGLOCATION, SHOWINGTURN, SHOWINGHELP, SHOWINGSTATUS, SHOWINGINVENTORY, GETTINGITEM, DEFEATED, ENDING
}
